name: Generate web page

on:
  push:
    paths:
    - fragments/**
    - in/**
    - layouts/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: davorg/aphra:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Create pages
      run: aphra build > aphra.log 2>&1

    - name: Archive aphra logs
      uses: actions/upload-artifact@v4
      with:
        name: aphra.log
        path: ./aphra.log
        retention-days: 3

    - name: Update pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

